---
- hosts: localhost
  become: yes
  tasks:
    - name: Ensure required packages are installed
      apt:
        name:
          - python3
          - python3-venv
          - python3-pip
          - git
        state: present
        update_cache: yes

    - name: Clone the Battleship game repository
      git:
        repo: 'https://github.com/9dot5/BattleShipGame-CS.git'
        dest: '~/git/BattleShipGame-CS'
        version: 'Joao_Santos'
        force: yes

    - name: Create virtual environment
      command: python3 -m venv ~/git/BattleShipGame-CS/venv
      args:
        creates: ~/git/BattleShipGame-CS/venv

    - name: Install requirements
      pip:
        requirements: ~/git/BattleShipGame-CS/requirements.txt
        virtualenv: ~/git/BattleShipGame-CS/venv

    - name: Ensure ZoKrates is installed
      shell: |
        curl -LSfs get.zokrates.dev | sh
        sudo mv zokrates /usr/local/bin/

    - name: Start the server
      shell: |
        source ~/git/BattleShipGame-CS/venv/bin/activate
        nohup python ~/git/BattleShipGame-CS/main.py &
      args:
        creates: /tmp/battleship_server_running

