- name: Setup Battleship Game Environment
  hosts: local
  become: yes
  vars:
    python_version: "3.8"
    venv_path: "/opt/battleship_env"
    project_path: "/opt/BattleShipGame-CS"
  tasks:
    - name: Ensure Python is installed
      apt:
        name: "python{{ python_version }}"
        state: present

    - name: Ensure pip is installed
      apt:
        name: python3-pip
        state: present

    - name: Install virtualenv
      pip:
        name: virtualenv
        executable: pip3

    - name: Create a virtual environment
      command: python3 -m venv {{ venv_path }}
      args:
        creates: "{{ venv_path }}/bin/activate"

    - name: Install required Python packages
      pip:
        requirements: "{{ project_path }}/requirements.txt"
        virtualenv: "{{ venv_path }}"
        executable: "{{ venv_path }}/bin/pip"

    - name: Copy project files
      copy:
        src: "{{ playbook_dir }}/../"
        dest: "{{ project_path }}"
        mode: 0755
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        remote_src: no
        exclude:
          - ".git"
          - "ansible"
